mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from polls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup',views.signup,name='signup')

    
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('kanmusu_syousai/<int:kanmusu_id>/vote/', views.vote, name='vote'),
    path('kanmusu', views.index2, name='index2'),
    path('kanmusu2', views.kanmusu_list, name='kanmusu_list'),
    path('kanmusu3', views.kanmusu_list2, name='kanmusu_list2'),
    path('kanmusu/<int:oogata_id>/', views.kanmusu_by_type, name='kanmusu_by_type'),
    path('kanmusu_syousai/<int:kanmusu_id>/', views.detail2, name='detail2'),
    path('seiyu', views.detail3, name='detail3'),
    path('seiyu/<int:seiyu_id>/', views.seiyu_syousai, name='seiyu_syousai'),
    path('seiyu/<int:seiyu_id>/tanto', views.seiyu_tanto ,name='seiyu_tanto'),
    path('kansyu',views.kansyu, name='kansyu'),
    path('kansyu/<int:kansyu_id>',views.kansyu_by_type, name='kansyu_by_type'),
    path('map_list',views.battle_name, name='map_list'),
    path('sanka_kanmusu/<int:battle_id>',views.sanka_kanmusu, name = 'sanka_kanmusu'),
    path('ivent', views.ivent, name='ivent'),
    path('ivent_naiyou/<int:name_id>',views.ivent_naiyou, name = 'ivent_naiyou'),####name_idはIventモデルの名前のこと
    path('nikkicreate',views.NikkiCreateView.as_view(),name='nikkicreate'),#フォーム
    path('nikkilist',views.NikkiListView.as_view(),name='nikkilist'),#リスト
    path('nikki/search',views.NikkiListQueryView.as_view(),name='nikkisearch'),#検索
    path('nikki/tagsearch/<int:pk>',views.NikkiTagListQueryView.as_view(),name='nikkitagsearch'),#タグ検索
    path('nikki/<int:pk>',views.NikkiDitaltView.as_view(),name='nikki'),#日記詳細
    path('commentcreate/<int:pk>/',views.CommentCreateView.as_view(),name='commentcreate'),#コメントフォーム
    path('questioncreate',views.QuestionCreateView.as_view(),name='questioncreate'),#質問フォーム
    path('question/<int:pk>',views.QuestionDitaltView.as_view(),name='question'),#質問詳細
    path('answercreate/<int:pk>/',views.AnswerCreateView.as_view(),name='answercreate'),#質問解答フォーム
    path('playquestion_list',views.QuestionListView.as_view(),name='question_list'),#質問リスト
    path('<int:answer_id>/like/', views.like, name='like'),
    path('<int:kanmusu_id>/kanmusu_ninnki/', views.kanmusu_ninnki, name='kanmusu_ninnki'),
    path('graph', views.graph, name='graph'),
    path('graph2', views.graph2, name='graph2'),
    path('api_map/<int:map_id>', views.api_map, name='api_map'),
   ]
                

polls/models.py
from django.db import models
from markdownx.models import MarkdownxField

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class Seiyu(models.Model):  
    name=models.CharField(max_length=200)
    seiyu_url=models.URLField(null=True,blank=True)
    seiyu_syozoku=models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    
class Eshi(models.Model):
    name=models.CharField(max_length=200)
    tw_url=models.URLField(null=True,blank=True)
    px_url=models.URLField(null=True,blank=True)    

    def __str__(self):
        return self.name

class Kansyu(models.Model):
    name=models.CharField(max_length=200)
    is_gunkan=models.BooleanField(default=False)
    setumei = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Oogata(models.Model): 
    typename=models.CharField(max_length=200)
    kansyu=models.ForeignKey(Kansyu, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.typename
    
    
class Kanmusu(models.Model):
    name=models.CharField(max_length=200,unique=True)
    kansyu=models.ForeignKey(Kansyu, on_delete=models.CASCADE)
    OOgata=models.ForeignKey(Oogata, on_delete=models.CASCADE)
    number=models.IntegerField(default=0)
    ichinin=models.CharField(max_length=200)
    Fsutairu=models.CharField(max_length=200)
    tokuchou=models.CharField(max_length=200)
    eshi = models.ForeignKey(Eshi, on_delete=models.CASCADE)
    seiyu = models.ForeignKey(Seiyu, on_delete=models.CASCADE)
    like_num = models.IntegerField(default=0)
    
    
    def __str__(self):
        return self.name
        
        
        
        
        
        
        
    


class Battle(models.Model):
    name=models.CharField(max_length=200)
    naiyo=models.CharField(max_length=1000)
    ido = models.CharField(max_length=100,null = True,blank = True)
    keido = models.CharField(max_length=100,null = True,blank = True)
    
    def __str__(self):
        return self.name
    

class Sanka_kanmusu(models.Model):
    battle=models.ForeignKey(Battle, on_delete=models.CASCADE)
    kanmusu=models.ForeignKey(Kanmusu, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.kanmusu.name
        
class Kansyu_setumei(models.Model):
    setumei=models.CharField(max_length=200)
    
    def __str__(self):
        return self.setumei
    
    
class Ivent(models.Model):
    name = models.CharField(max_length=200)
    pub_date = models.DateField(null = True,blank = True)
    
    def __str__(self):
        return self.name
    
class Ivent_naiyou(models.Model):
    ivent = models.ForeignKey(Ivent, on_delete=models.CASCADE)
    naiyou = models.CharField(max_length=200)
    
    def __str__(self):
        return self.naiyou
        
class Tokkokanmusu(models.Model):
    ivent_naiyou = models.ForeignKey(Ivent_naiyou, on_delete=models.CASCADE)
    kanmusu = models.ForeignKey(Kanmusu, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.kanmusu.name
        
from django.utils import timezone
from django.contrib.auth.models import User

    
class Tag(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name
    

        
class Playnikki(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    title = models.CharField(max_length=20)
    nikki = MarkdownxField(max_length=2000)
    image = models.ImageField(upload_to='media',blank=True, null=True)
    tag = models.ManyToManyField(Tag, verbose_name='タグ', blank=True)
    
    
    
class Comment(models.Model):
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('本文')
    target = models.ForeignKey(Playnikki, on_delete=models.CASCADE, verbose_name='対象記事')
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return self.text[:20]    
        
        
# 質問モデル        
class PlayQuestion(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    question_text = models.TextField('本文')
    pub_date = models.DateTimeField('date published',default=timezone.now)
    tag = models.ManyToManyField(Tag, verbose_name='タグ', blank=True)
    image = models.ImageField(upload_to='media',blank=True, null=True)
    title = models.CharField(max_length=20)



# 質問の回答
class Answer(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField('本文')
    target = models.ForeignKey(PlayQuestion, on_delete=models.CASCADE, verbose_name='対象記事')
    pub_date = models.DateTimeField('date published',default=timezone.now)
    like_num = models.IntegerField(default=0)

    class Meta:
        ordering = ['-pub_date']

# いいね機能
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='like_user')
    target = models.ForeignKey(Answer, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published',default=timezone.now)


#艦娘人気投票
class Kannmusu_like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='kannmusu_like_user')
    target = models.ForeignKey(Kanmusu, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published',default=timezone.now)
    
    
class Map(models.Model):
    map_name = models.CharField(max_length=100)
    jyusyo = models.CharField(max_length=100)
    ido = models.CharField(max_length=100)
    keido = models.CharField(max_length=100)
    kanmusu = models.ManyToManyField(Kanmusu, blank=True)

    def __str__(self):
        return self.map_name

polls/forms.py
from django import forms
from .models import Playnikki,Comment,PlayQuestion,Answer

class Nikkiform(forms.ModelForm):
    class Meta:
        model = Playnikki
        exclude = ('tag','user')
        
TagInlineFormSet = forms.inlineformset_factory(
    Playnikki, Playnikki.tag.through, fields='__all__', can_delete=False
)
        
        
class Commentform(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('target','pub_date')
        
        
class Questionform(forms.ModelForm):
    class Meta:
        model = PlayQuestion
        exclude = ('pub_date','user')#「 , 」を付けないと[python manage.py makemigrations]が出来なかった
        
TagInlineFormSet = forms.inlineformset_factory(
    PlayQuestion, PlayQuestion.tag.through, fields='__all__', can_delete=False
)


class Answerform(forms.ModelForm):
    class Meta:
        model = Answer
        exclude = ('user','target','pub_date')

polls/templates/polls/api_map.html
{% extends 'polls/base.html' %} {% block content %} {% load md %} {% load static %}

<body>
{% if map %}
<ul>
  <li>{{map.map_name}}</li>
  <li>{{map.jyusyo}}</li>
  {% for kanmusu in map.kanmusu.all %}
    <li>{{kanmusu.name}}</li>
  {% endfor %}
</ul>

{% else %}
    <p>No polls are available.</p>
{% endif %}
    <!--{% for tag in playnikki.tag.all %}-->
    <!--<p><button type="button" class="btn btn-primary btn-sm">{{tag.name}}</button></p>-->
    <!--{% endfor %}-->




<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC94_hScZ7P8qqD5WzrGrxnjcXEw3gknpw&callback=initMap" async></script>
<script type="text/javascript">
  var map;
  var marker;
  var geocoder;
  function initMap() {
    geocoder = new google.maps.Geocoder();
    geocoder.geocode({
    'address': '{{map.ido}},{{map.keido}}' //住所map.jyusyoを緯度経度の数値にすればOK
    }, function(results, status) {
      if (status === google.maps.GeocoderStatus.OK) {
      map = new google.maps.Map(document.getElementById('gmap'), {
        center: results[0].geometry.location,
        zoom: 17 //ズーム
     });
    marker = new google.maps.Marker({
    position: results[0].geometry.location,
    map: map
    });
    infoWindow = new google.maps.InfoWindow({
    content: '<h4>{{map.map_name}}</h4>'
    });
    marker.addListener('click', function() {
      infoWindow.open(map, marker);
    });
    } else {
      alert(status);
    }
  });
}
</script>
<div id="gmap"></div>

<style type="text/css">
#gmap {
    width:50%;
   height:400px;
}</style>

</body>

<!--<h1>{{ seiyu.name }}</h1>-->
<!--<ul>-->
<!--    <li>{{ seiyu.seiyu_url }}</li>-->
<!--    <li>{{ seiyu.seiyu_syozoku}}</li>-->
    
<!--</ul>-->


<!--class Map(models.Model):-->
<!--    map_name = models.CharField(max_length=100)-->
<!--    jyusyo = models.CharField(max_length=100)-->
<!--    kanmusu = models.ManyToManyField(Kanmusu, blank=True)-->

<!--    def __str__(self):-->
<!--        return self.map_name-->

<!--def api_map(request,map_id):-->
<!--    map = get_object_or_404(Map,pk=map_id)-->
<!--    return render(request, 'polls/api_map.html')-->

{% endblock %}

polls/templates/polls/base.html
{% load static%}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<body>
    <nav class="navbar navbar-light bg-light">
        <a class="text-danger navbar-brand "  href="/">艦これオリジナルサイト</a>
        {%if user.is_authenticated %} <!-- ユーザー認証されていれば、以下の２つのボタンが表示される　-->
          <button class="btn btn-outline-success" type="button"><a href="{% url 'nikkicreate' %}">投稿する</a></button>
          <button class="btn btn-outline-success" type="button"><a href="{% url 'questioncreate' %}">質問を投稿する</a></button>
          <button class="btn btn-outline-success" type="button"><a href="{% url 'question_list' %}">質問一覧</a></button>
          <button class="btn btn-outline-success" type="button"><a href="{% url 'logout' %}">ログアウト</a></button>
        {% else %}
          <button class="btn btn-outline-success" type="button"><a href="{% url 'login' %}">ログイン</a></button>
          <button class="btn btn-outline-success" type="button"><a href="{% url 'signup' %}">ユーザー登録</a></button>
        {% endif %}
          <form class="form-inline my-2 my-lg-0" action="{% url 'nikkisearch' %}" method="get">
            <input class="form-control mr-sm-2"  placeholder="Search"name="query" value="{{ request.GET.query }}" type="text">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form> 
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index2' %}">艦娘リスト</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'graph' %}">艦娘人気グラフ</a>
            </li>
          </ul>
          <span class="navbar-text">
            Navbar text with an inline element
          </span>
        </div>
    </nav>
    <div class="alert alert-primary border border-danger" role="alert">
          ようこそ　艦これの世界へ！！
    </div>
    {% if messages %}
    		{% for message in messages %}
    		<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
          <strong>{{ message }}</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
    		</div>
    		{% endfor %}

    		
    		
      </ul>
    {% endif %}
  <div class="content container">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-sm-8 col-8">
              
              {% load md %}
              {% block content %}
              
              
              {% endblock %}
          </div>
          <div class="col-sm-4 col-4">
            <div class="col-sm-12 col-md-12">
              <iframe width="350" height='250'  src="https://www.youtube.com/embed/KNkdcm1e2Xk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              <!--<iframe src="https://www.youtube.com/embed/KNkdcm1e2Xk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>-->
            </div>
            <div class="row">
              <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                　　　　　　タグ一覧　　　　　　　
              </a>
              {% if tag %}
                <div class="collapse" id="collapseExample">
                  <div class="col-sm-6 col-md-6">
                    {% for tag in tag.all %}
                      <a class="btn btn-primary mt-1" href="{% url 'nikkitagsearch' tag.id %}" role="button">{{tag.name}}</a>
                    {% endfor %}  
                  </div>
                </div>
              {% else %}
                  <p>No polls are available.</p>
              {% endif %}
            </div>    
            <a class="twitter-timeline" data-height="500"  data-theme="dark" href="https://twitter.com/KanColle_STAFF?ref_src=twsrc%5Etfw">Tweets by KanColle_STAFF</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          </div>
        </div>  
      </div>
    </div>
    <h2>各種艦これリスト</h2>

    <div class="col-sm-12 col-md-12">
      <div class="row">
        <div class='col-md-6 col-lg-4 '>
          <div class='alert alert-primary border-info' role="alert">
          <a href="{% url 'graph' %}"><p  class='text-center mb-0 font-weight-bold'>艦これ人気ランキング</p></a>
          </div>
        </div>
        <div class='col-md-6 col-lg-4'> 
          <div class = 'alert alert-primary border-info' role="alert">
            <a href= "{% url 'kanmusu_list2' %}"><p  class='text-center mb-0 font-weight-bold'>艦種別スタイル</p></a>
          </div>
        </div>
        <div class='col-md-6 col-lg-4'>
          <div class = 'alert alert-primary border-info' role="alert">
            <a href= "{% url 'detail3' %}"><p  class='text-center mb-0 font-weight-bold'>艦これ声優リスト</p></a>
          </div>
        </div>
        <div class='col-md-6 col-lg-4'>
          <div class = 'alert alert-primary border-info' role="alert">
            <a href= "{% url 'kansyu' %}"><p  class='text-center mb-0 font-weight-bold'>艦これ艦種リスト</p></a>
          </div>
        </div>
        <div class='col-md-6 col-lg-4'>
          <div class = 'alert alert-primary border-info' role="alert">
            <a href="{% url 'map_list' %}"><p  class='text-center mb-0 font-weight-bold'>聖地・戦地リスト</p></a>
          </div>
        </div>
        <div class='col-md-6 col-lg-4'>
          <div class = 'alert alert-primary border-info' role="alert">
            <a href="{% url 'ivent' %}"><p  class='text-center mb-0 font-weight-bold'>過去イベント</p></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

polls/templates/polls/battle.html
{% extends 'polls/base.html' %}

{% block content %}



{% if latest_battle_name %}
    <ul>
    <p>作戦名</p>
    {% for battle_name in latest_battle_name %}
        <li>{{battle_name.name}} 　　　　<a href='{% url "sanka_kanmusu" battle_name.id %}'> 参加艦娘</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/battle_in_kanmusu.html
{% extends 'polls/base.html' %}

{% block content %}



{% if sanka_kanmusu_list %}
    <ul>
<a href="/polls/">トップページ</a> 

<h4>{{battle.name}}</h4>
    <p>艦娘名</p>
    {% for sanka_kanmusu in sanka_kanmusu_list %}
        <li><a href="{% url 'detail2' sanka_kanmusu.kanmusu.id %}">{{ sanka_kanmusu.kanmusu.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/form.html
{% extends "polls/base.html" %}

{% block content %}

{% load widget_tweaks %}
{% load static %}


<body>
    

    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">


        <form method="post"  enctype="multipart/form-data">
                {% csrf_token %}
            
                <p>ユーザー名</p>
                <p>{{ form.user |add_class:"form-control"}}</p>
                <p>投稿日時</p>
                <p>{{ form.pub_date |add_class:"form-control"}}</p>
                <div class="form-row">
                        <div class="form-group col-md-6">
                         <label for="inputEmail4">タイトル</label>
                         {{ form.title |add_class:"form-control"}}
                        </div>
                </div>        
                <p>{{ form.nikki|add_class:"form-control" }}</p>
                <p>画像</p>
                <p>{{form.image |add_class:"form-control-file"}}</p>
                <h2>タグ</h2>
                    {{ formset.management_form }}
                    {% for tag_form in formset %}
                        {{ tag_form.as_p }}
                        <hr>
                     {% endfor %}
                
                
                <p><button type="submit">save</button></p>
        </form>
{{ form.media }}

</body>

{% endblock %}

   

polls/templates/polls/form_comment.html
{% extends "polls/base.html" %} <!--コメント用のテンプレート-->

{% block content %}

{% load widget_tweaks %}
{% load static %}


<body>
    

    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">


<form method="post"  enctype="multipart/form-data">
        {% csrf_token %}
    
        <p>ユーザー名</p>
        <p>{{ form.name |add_class:"form-control"}}</p>
        <div class="form-row">
        </div>        
        <p>{{ form.text|add_class:"form-control" }}</p>

        
        <p><button type="submit">save</button></p>
</form>

</body>

{% endblock %}

polls/templates/polls/ivent.html
{% extends 'polls/base.html' %}

{% block content %}



{% if ivents %}
    <ul>
<a href="/polls/">トップページ</a>    
    <p>過去イベントリスト</p>
    {% for ivent in ivents %}
        <li><a href = "{% url 'ivent_naiyou' ivent.id %}">{{ ivent.name}}</a></li>　　
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/kanmusu_name.html
{% extends 'polls/base.html' %}

{% block content %}



{% if latest_kanmusu_list %}
    <ul>
<a href="/polls/">トップページ</a>    
    <p>艦娘名</p>
    {% for kanmusu in latest_kanmusu_list %}
        <li><a href="{% url 'detail2' kanmusu.id %}">{{ kanmusu.name}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/kansyu_by_type.html
{% extends 'polls/base.html' %}

{% block content %}

<h1>艦種リスト</h1>
{% if oogatas %}
    <ul>
    {% for oogata in oogatas %}    
        <li><a href="{% url 'kanmusu_by_type' oogata.id %}">{{oogata.typename}}</a></li>
    {% endfor %}
    </ul>
{% endif %}

{% endblock %}

polls/templates/polls/seiyu.syousai.html
{% extends 'polls/base.html' %}

{% block content %}

<h1>{{ seiyu.name }}</h1>
<ul>
    <li>{{ seiyu.seiyu_url }}</li>
    <li>{{ seiyu.seiyu_syozoku}}</li>
    
</ul>

{% endblock %}

polls/templates/polls/top_page.html
{% extends 'polls/base.html' %} {% block content %} {% load md %} {% load static %}

<body>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"> {% if playnikki_list %}
    <div class="card-group">
            {% for playnikki in playnikki_list %}
                <div class="col-sm-6 col-md-6">
                    <div class="card border-dark m-1">
                        {% if playnikki.image %} 　<img src="{{ playnikki.image.url }}" class="card-img-top" alt="..."> {% endif %}
                        <div class="card-body">
                            <a href="{% url 'nikki' playnikki.id %}">
                                <h3><class="card-title">{{playnikki.title}}</h3>
                            </a>
                            <h4 class="card-subtitle mb-2 text-muted">{{playnikki.user.username}}</h4>
                            <h6 class="card-subtitle mb-2 text-muted">{{playnikki.pub_date}}</h6>
                            <p class="card-text">{{playnikki.nikki| mark_down_to_text |truncatechars:30 }}</p>
                            {% for tag in playnikki.tag.all %}
                            <p><button type="button" class="btn btn-primary btn-sm">{{tag.name}}</button></p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
        <div class = "container ">
            <div class = "row justify-content-center">
                <div class = " alert alert-primary" role="alert">
                    <div class = "text-center">
                        <h4><a href= "{% url 'nikkilist' %}"><p  class='text-center m-0 mt-2  font-weight-bold'>過去の投稿一覧へ</p></a></h4>
                    </div>
                </div>
            </div>
        </div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3256.962468685579!2d139.66652191462933!3d35.28205938028928!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60184074f0111e63%3A0x9d4f8d7d998507f9!2z44CSMjM4LTAwMDgg56We5aWI5bed55yM5qiq6aCI6LOA5biC5aSn5rud55S677yR5LiB55uu77yZ!5e0!3m2!1sja!2sjp!4v1590581304037!5m2!1sja!2sjp" width="400" height="250" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
</body>
{% endblock %}